
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221ce4bdd0e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('main_wallet', sa.Float(), nullable=False),
    sa.Column('play_wallet', sa.Float(), nullable=False),
    sa.Column('coin', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sms_text', sa.Text(), nullable=True),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('receiver_phone', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('transaction_date', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PENDING_ADMIN_APPROVAL', 'APPROVED', 'REJECTED', name='depositstatus'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_reference'), 'deposits', ['reference'], unique=False)
    op.create_index(op.f('ix_deposits_status'), 'deposits', ['status'], unique=False)
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='transferstatus'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_receiver_id'), 'transfers', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_transfers_sender_id'), 'transfers', ['sender_id'], unique=False)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telebirr_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='withdrawalstatus'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_status'), 'withdrawals', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawals_user_id'), 'withdrawals', ['user_id'], unique=False)
    op.create_table('used_sms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_number', sa.String(length=128), nullable=False),
    sa.Column('sms_hash', sa.String(length=64), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number', name='uq_used_sms_reference')
    )
    op.create_index(op.f('ix_used_sms_reference_number'), 'used_sms', ['reference_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_used_sms_reference_number'), table_name='used_sms')
    op.drop_table('used_sms')
    op.drop_index(op.f('ix_withdrawals_user_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_status'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_sender_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_receiver_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_status'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_reference'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
